// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXhVOzLmyU1BnMZC9cd17KrPgclRDDK7g',
    appId: '1:761300202645:web:978fbf235ce4fb2c3f179c',
    messagingSenderId: '761300202645',
    projectId: 'flutternoorden',
    authDomain: 'flutternoorden.firebaseapp.com',
    storageBucket: 'flutternoorden.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0soEwLb-PInasY6oV_T1T1sAu1n3yZFQ',
    appId: '1:761300202645:android:b372649af2d234a03f179c',
    messagingSenderId: '761300202645',
    projectId: 'flutternoorden',
    storageBucket: 'flutternoorden.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKcuRXWIaK576rNhHvlF5kh9wj-HWSDBI',
    appId: '1:761300202645:ios:64d5aa1569f8fe863f179c',
    messagingSenderId: '761300202645',
    projectId: 'flutternoorden',
    storageBucket: 'flutternoorden.firebasestorage.app',
    iosBundleId: 'com.example.noorden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKcuRXWIaK576rNhHvlF5kh9wj-HWSDBI',
    appId: '1:761300202645:ios:64d5aa1569f8fe863f179c',
    messagingSenderId: '761300202645',
    projectId: 'flutternoorden',
    storageBucket: 'flutternoorden.firebasestorage.app',
    iosBundleId: 'com.example.noorden',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXhVOzLmyU1BnMZC9cd17KrPgclRDDK7g',
    appId: '1:761300202645:web:a7a1cc7e85f3b5523f179c',
    messagingSenderId: '761300202645',
    projectId: 'flutternoorden',
    authDomain: 'flutternoorden.firebaseapp.com',
    storageBucket: 'flutternoorden.firebasestorage.app',
  );
}
